name: lily_jigsaw_puzzle
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.2
  shared_preferences: ^2.3.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/puzzle-1.jpg
    - assets/images/puzzle-2.jpg
    - assets/images/puzzle-3.jpg
    - assets/images/puzzle-4.jpg
    - assets/images/puzzle-5.jpg
    - assets/images/puzzle-6.jpg
    - assets/images/puzzle-7.jpg
    - assets/images/puzzle-8.jpg
    - assets/images/puzzle-9.jpg
    - assets/icons/
